# x,y,z=input().split("-")
# print(x)
# print(type(x))
# print(y)
# print(z)
# print(int(x)+int(y))
# x=input()
# y=input()
# print(int(x)//int(y))
# x=int(input())
# y=int(input())
# z=(x<y)
# a=(x>y)
# b=not(z and a)
# print(b)
